import Head from "next/head";
import fs from "fs";
import path from "path";
import matter from "gray-matter";
import BlogCard from "@/components/BlogCard";

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Abbas' Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-4/5 flex justify-center items-center mx-auto mt-16">
        <div className="w-4/5 grid sm:grid-cols-2 md:grid-cols-3 2xl:grid-cols-4 gap-6">
          {posts.map((post, index) => (
            <BlogCard key={index} post={post} />
          ))}
        </div>
        <div className="w-1/5 "></div>
      </div>
    </>
  );
}

export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join("src", "posts"));

  const posts = files.map((filename) => {
    // Create slug
    const slug = filename.replace(".mdx", "");
    // Get frontmatter
    const markdownWithMeta = fs.readFileSync(
      path.join("src", "posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);

    return {
      slug,
      frontmatter,
    };
  });

  return {
    props: {
      posts,
    },
  };
};
